### ISSUE TITLE
Problem with the characters (Portuguese Language - on linux)

### ISSUE THREAD

**Issue by lucasrocha7111** [buffonomics/epicworship#5]
Hi,

I like so much this software, thank you for made this.

But on linux I have a problem.

See this picture:

![epic_problem](https://cloud.githubusercontent.com/assets/11205535/7666566/2253ae74-fbc1-11e4-879f-1f9ff92a2500.png)

This problem in bible, I can't search the book, because of wrong letter.
(Letter with portuguese accentuation like: ã, á, ç e etc)

Have this problem on songs too:

![epic_problem2](https://cloud.githubusercontent.com/assets/11205535/7666584/7e0cae46-fbc1-11e4-9535-eb61856015a4.png)

I think this problem can be solve with a charset UTF-8 configuration. (Always works in web system =])

Thank you.

**Comment by italopoiema** [comment]
Hi,
You can just change inside the file Launch_MacLinux.sh

Original file
> cd `dirname $0`
> java -jar -Djavafx.autoproxy.disable=true "epicworship-1.4.8.0.jar"

With charset modifier
> cd `dirname $0`
> java -jar -Djavafx.autoproxy.disable=true **-Dfile.encoding=ISO-8859-1** "epicworship-1.4.8.0.jar"

God bless you

**Comment by lucasrocha7111** [comment]
Thank you Italo.

This solve my problem.
The songs I can change manually, or load the standard songs again e problem solve. =]
The bible work fine automatically.

Thank you.
God bless you.

**Comment by buffonomics** [comment]
@italopoiema You rock dude.
Thanks for that.
